---
title: "Prak 01 Visdat"
author: "Angga Fathan Rofiqy (G1401211006)"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    self_contained: true
    thumbnails: false
    lightbox: true
    gallery: true
    highlight: tango
    code_folding: show
    toc_depth: 5
    number_sections: false
    theme: flatly
    toc: yes
    toc_float:
      collapsed: true
      smooth_scroll: true
    fig_caption: true
---

```{r setup, include=FALSE, echo=FALSE, warning=FALSE, message = FALSE}
#                      -=( Install & Load Package Function )=-
install_load <- function (package1, ...)  {   

   # convert arguments to vector
   packages <- c(package1, ...)

   # start loop to determine if each package is installed
   for(package in packages){

       # if package is installed locally, load
       if(package %in% rownames(installed.packages()))
          do.call('library', list(package))

       # if package is not installed locally, download, then load
       else {
          install.packages(package)
          do.call("library", list(package))
       }
   } 
}

install_load("ggplot2","viridis")
# install.packages("ggplot2"); library(ggplot2)
# install.packages("viridis"); library(viridis)
# webshot::install_phantomjs()

path <- function() gsub  ( "\\\\",  "/",  readClipboard ()  )
```

```{r , include=FALSE, echo=FALSE, warning=FALSE, message = FALSE}
#Set Working Directory
require("knitr")
opts_knit$set(root.dir = "C:/Users/Fathan/Documents/Obsidian Vault/2. Kuliah/Smt 7 & 8/Visdat-25/Prak 02")
```

```{r}
setwd("C:/Users/Fathan/Documents/Obsidian Vault/2. Kuliah/Smt 7 & 8/Visdat-25/Prak 02")
```

# Data

## Import Data

> Data Susenas Provinsi Jawa Barat tahun 2020

```{r}
susenas <- read.csv("Data/Susenas Jawa Barat 2020.csv", sep = ";")
head(susenas)
```

```{r}
namakabupaten<-read.csv("Data/nama kabupaten.csv",sep = ",")
head(namakabupaten)
```

## Data P**reprocessing** 

```{r}
datakab <- namakabupaten[
  namakabupaten$nama_prov == "JAWA BARAT", 
  c("nama_kab", "kab")
]
colnames(datakab) <- c("Nama Kabupaten", "KabKota")

data <- merge(susenas, datakab, by="KabKota")
head(data)
```

## Data Quality Checking

```{r}
sum(is.na(data))
```

```{r}
str(data)
```

```{r}
table(data[data$`Nama Kabupaten` == "BANDUNG", ]$KabKota)
```

# Bar Chart

## Sederhana

```{r fig.height=3.5, fig.width=10, dpi=300}
ggplot(data, aes(Status_Rawan)) + 
  geom_bar()
```

> **Dengan Warna**

```{r fig.height=3.5, fig.width=10, dpi=300}
ggplot(data, aes(Status_Rawan, fill=Status_Rawan)) + 
  geom_bar()
```

> **Warna Viridis**

```{r fig.height=3.5, fig.width=10, dpi=300}
ggplot(data, aes(Status_Rawan, fill=Status_Rawan)) + 
  geom_bar() + 
  scale_fill_viridis(discrete = T)
```

## Banyak Kategori

```{r fig.height=3.5, fig.width=10, dpi=300}
ggplot(data, aes(`Nama Kabupaten`, fill=`Nama Kabupaten`)) + 
  geom_bar() + 
  scale_fill_viridis(discrete = T)
```

> **Ubah angle text**

```{r fig.height=5, fig.width=10, dpi=300}
ggplot(data, aes(`Nama Kabupaten`, fill=`Nama Kabupaten`)) + 
  geom_bar() + 
  scale_fill_viridis(discrete = T) + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```

```{r fig.height=5, fig.width=10, dpi=300}
ggplot(data, aes(`Nama Kabupaten`, fill=`Nama Kabupaten`)) + 
  geom_bar() + 
  scale_fill_viridis(discrete = T) + 
  theme(axis.text.x = element_text(angle = 75, vjust = 1, hjust = 1))
```

> **Hapus legend**

```{r fig.height=3.5, fig.width=10, dpi=300}
ggplot(data, aes(`Nama Kabupaten`, fill=`Nama Kabupaten`)) + 
  geom_bar() + 
  scale_fill_viridis(discrete = T) + 
  theme(axis.text.x = element_text(angle = 75, vjust = 1, hjust = 1), 
        legend.position = "none") + ylab("Frekuensi")
```

> **Rotasi Barchart**

```{r fig.height=3.5, fig.width=10, dpi=300}
ggplot(data, aes(y = `Nama Kabupaten`, fill=`Nama Kabupaten`)) + 
  geom_bar() + 
  scale_fill_viridis(discrete = T) + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1), 
        legend.position = "none") + 
  xlab("Frekuensi")
```

```{r fig.height=3.5, fig.width=10, dpi=300}
ggplot(data, aes(`Nama Kabupaten`, fill=`Nama Kabupaten`)) + 
  geom_bar() + 
  scale_fill_viridis(discrete = T) + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1), 
        legend.position = "none") + 
  ylab("Frekuensi") + 
  coord_flip() + 
  ggtitle("Diagram Batang Kabupaten")
```

# Grouped Bar Chart

```{r fig.height=3.5, fig.width=10, dpi=300}
ggplot(data, aes(x=`Nama Kabupaten`, fill=Status_Rawan)) + 
  geom_bar(position="dodge")
```

```{r fig.height=3.5, fig.width=10, dpi=300}
ggplot(data, aes(x=`Nama Kabupaten`, fill=Status_Rawan)) + 
  geom_bar(position="dodge") + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  scale_fill_viridis(discrete = T)
```

## Stacked Barchart

```{r fig.height=3.5, fig.width=10, dpi=300}
ggplot(data, aes(x=`Nama Kabupaten`, fill=Status_Rawan)) + 
  geom_bar(position="stack")
```

## Stacked Barchart 100%

```{r fig.height=3.5, fig.width=10, dpi=300}
ggplot(data, aes(x=`Nama Kabupaten`, fill=Status_Rawan)) + 
  geom_bar(position="fill")
```

```{}
```

```{r fig.height=3.5, fig.width=10, dpi=300}
ggplot(data, aes(x=`Nama Kabupaten`, fill=Status_Rawan)) + geom_bar(position="dodge") + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) + scale_fill_manual(values = c("red", "green"))
```

```{r}
ggplot(data, aes(x=`Nama Kabupaten`, fill=Air_Minum_Layak)) + geom_bar(position="dodge") + scale_fill_viridis(discrete = T) + facet_wrap(~Status_Rawan) + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```

#Stacked Bar Chart

```{r}
ggplot(data, aes(x=`Nama Kabupaten`, fill=Status_Rawan)) + geom_bar(position="fill") + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```

```{r}
library(dplyr)
percentDatadaerah <- data %>% 
  group_by(`Nama Kabupaten`) %>% 
  count(Status_Rawan) %>% 
  mutate(ratio=scales::percent(n/sum(n)))
head(percentDatadaerah)
```

```{r}
ggplot(data, aes(x=`Nama Kabupaten`, fill=Status_Rawan)) + geom_bar(position="fill") + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))+ geom_text(data=percentDatadaerah,aes(y=n,label=ratio),color="white",position=position_fill(vjust=0.5),size = 2)
```

Mewarnai manual

```{r}
ggplot(data, aes(x=`Nama Kabupaten`, fill=Status_Rawan)) + geom_bar(position="fill") + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) + geom_text(data=percentDatadaerah,aes(y=n,label=ratio),color="white",position=position_fill(vjust=0.5),size = 2)+scale_fill_manual(values=c("#7be217", "#4f58ab"))
```

#Lollipop Chart

```{r}
table(data$`Nama Kabupaten`)
```

```{r}
head(percentDatadaerah)
```

```{r}
percentDatadaerah2 <- percentDatadaerah[percentDatadaerah$Status_Rawan=="Rawan",]
percentDatadaerah2 <- as.data.frame(percentDatadaerah2)
```

```{r}
ggplot(percentDatadaerah2, aes(x = `Nama Kabupaten`, y = n)) + geom_segment(aes(x = `Nama Kabupaten`, xend = `Nama Kabupaten`, y = 0, yend = n)) + geom_point() 
```

Option 1: coord_flip

```{r}
ggplot(percentDatadaerah2, aes(x = `Nama Kabupaten`, y = n)) + geom_segment(aes(x = `Nama Kabupaten`, xend = `Nama Kabupaten`, y = 0, yend = n)) + geom_point() + coord_flip()
```

Option 2: Ubah X dan Y

```{r}
ggplot(percentDatadaerah2, aes(y = `Nama Kabupaten`, x = n)) + geom_segment(aes(y = `Nama Kabupaten`, yend = `Nama Kabupaten`, x = 0, xend = n)) + geom_point()
```

```{r}
ggplot(percentDatadaerah2, aes(x = `Nama Kabupaten`, y = n)) + geom_segment(aes(x = `Nama Kabupaten`, xend = `Nama Kabupaten`, y = 0, yend = n)) + geom_point() + coord_flip() + geom_point(size = 4, pch = 21, bg = 5, col = 6)
```

```{r}
ggplot(percentDatadaerah2, aes(x = `Nama Kabupaten`, y = n)) + geom_segment(aes(x = `Nama Kabupaten`, xend = `Nama Kabupaten`, y = 0, yend = n), color="grey", lwd=1.5) + geom_point() + coord_flip() + geom_point(size = 5, pch = 21, bg = 6, col = 1) + theme_classic()
```

```{r}
ggplot(percentDatadaerah2, aes(x = `Nama Kabupaten`, y = n)) + geom_segment(aes(x = `Nama Kabupaten`, xend = `Nama Kabupaten`, y = 0, yend = n), color="grey", lwd=1.5) + geom_point() + coord_flip() + geom_point(size = 5, pch = 21, bg = 6, col = 1) + theme_classic()
```

```{r}
ggplot(percentDatadaerah2, aes(x = `Nama Kabupaten`, y = n)) + geom_segment(aes(x = `Nama Kabupaten`, xend = `Nama Kabupaten`, y = 0, yend = n), color="grey", lwd=1.5) + geom_point() + coord_flip() + geom_point(size = 5, pch = 21, bg = 6, col = 1) + geom_text(aes(label = n), color = "white", size = 2) + theme_classic() 
```

```{r}
x = reorder(percentDatadaerah2$`Nama Kabupaten`, percentDatadaerah2$n)
x
```

```{r}
ggplot(percentDatadaerah2, aes(x = reorder(`Nama Kabupaten`, n), y = n)) + geom_segment(aes(xend = `Nama Kabupaten`, y = 0, yend = n), color="grey", lwd=1.5) + geom_point() + coord_flip() + geom_point(size = 5, pch = 21, bg = 6, col = 1) + geom_text(aes(label = n), color = "white", size = 2) + theme_classic()
```
